version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    env_file:
      - .env
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  node-app:
    build: .
    image: node-app
    environment:
      - NODE_PORT=${NODE_PORT}
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
